# Generated by Django 5.0 on 2024-02-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_remove_asset_asset_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
    ]
