# Generated by Django 5.0 on 2024-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_asset_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(default=True, max_length=128),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.IntegerField(default=True),
        ),
    ]
