# Generated by Django 5.0 on 2024-02-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_asset_asset_number_alter_asset_serial_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name_plural': 'AssetCategories'},
        ),
    ]
