# Generated by Django 5.0 on 2024-02-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_asset_asset_number_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.IntegerField(unique=True),
        ),
    ]
