# Generated by Django 5.0.2 on 2024-02-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_asset_asset_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_number',
        ),
    ]
